<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>GameNamespace</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FlatRedBall2.MonoGame" />
    <PackageReference Include="MonoGame.Framework.DesktopGL" />
  </ItemGroup>
</Project>
