<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>MusicPitchWebSpike</RootNamespace>
    <AssemblyName>MusicPitchWebSpike</AssemblyName>
    <DefineConstants>$(DefineConstants);BLAZORGL</DefineConstants>
    <KniPlatform>BlazorGL</KniPlatform>
    <BlazorEnableTimeZoneSupport>false</BlazorEnableTimeZoneSupport>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="nkast.Xna.Framework" />
    <PackageReference Include="nkast.Xna.Framework.Graphics" />
    <PackageReference Include="nkast.Xna.Framework.Audio" />
    <PackageReference Include="nkast.Xna.Framework.Input" />
    <PackageReference Include="nkast.Xna.Framework.Game" />
    <PackageReference Include="nkast.Kni.Platform.Blazor.GL" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MusicPitchWebSpike.Common\MusicPitchWebSpike.Common.csproj" />
    <ProjectReference Include="..\..\..\src\FlatRedBall2.BlazorGL\FlatRedBall2.BlazorGL.csproj" />
  </ItemGroup>

</Project>
