# Links every 3rd-party skill in /frb-skills/ into /.claude/skills/ so Claude Code discovers it
# while working on the engine, and regenerates the matching block in .gitignore. Safe to re-run.
# Windows needs Developer Mode enabled for unprivileged symlinks.

$ErrorActionPreference = 'Stop'
$root = Resolve-Path (Join-Path $PSScriptRoot '..')
$skillsDir = Join-Path $root '.claude/skills'
$names = Get-ChildItem (Join-Path $root 'frb-skills') -Directory | ForEach-Object Name | Sort-Object
$onWindows = $env:OS -eq 'Windows_NT'

foreach ($name in $names) {
    $link = Join-Path $skillsDir $name
    $item = Get-Item $link -Force -ErrorAction SilentlyContinue
    if ($item -and $item.LinkType) { continue }
    if ($item) {
        # A real folder here shadows the canonical copy and silently goes stale.
        throw ".claude/skills/$name is a real folder, not a link. Delete it (the canonical copy is frb-skills/$name) and re-run."
    }
    $target = "../../frb-skills/$name"
    if ($onWindows) {
        # mklink uses the unprivileged Developer Mode path; New-Item -ItemType SymbolicLink can demand elevation.
        cmd.exe /c mklink /D $link ($target -replace '/', '\') | Out-Null
        if ($LASTEXITCODE -ne 0) { throw "mklink failed for $name. Is Windows Developer Mode on?" }
    } else {
        New-Item -ItemType SymbolicLink -Path $link -Target $target | Out-Null
    }
    Write-Host "linked $name"
}

# Remove links whose skill was deleted or renamed in frb-skills.
Get-ChildItem $skillsDir -Force | Where-Object { $_.LinkType -and $names -notcontains $_.Name } | ForEach-Object {
    $_.Delete()
    Write-Host "removed stale link $($_.Name)"
}

$gitignore = Join-Path $root '.gitignore'
$begin = '# BEGIN frb-skills links (generated by tools/link-skills.ps1)'
$end = '# END frb-skills links'
$text = [IO.File]::ReadAllText($gitignore)
$block = (@($begin) + ($names | ForEach-Object { "/.claude/skills/$_" }) + @($end)) -join "`n"
$pattern = [regex]::Escape($begin) + '[\s\S]*?' + [regex]::Escape($end)
if ($text -notmatch $pattern) { throw ".gitignore is missing the '$begin' marker block." }
$updated = [regex]::Replace($text, $pattern, { param($m) $block })
if ($updated -ne $text) {
    [IO.File]::WriteAllText($gitignore, $updated)
    Write-Host 'updated .gitignore'
}
